CMAKE_MINIMUM_REQUIRED(VERSION 2.8.12 FATAL_ERROR)

PROJECT(pthreadpool-download NONE)

INCLUDE(ExternalProject)
ExternalProject_Add(pthreadpool
	GIT_REPOSITORY https://github.com/Maratyszcza/pthreadpool.git
	GIT_TAG 5690b5ceada160444a916d31ef72e381f5e52d67
	SOURCE_DIR "${CONFU_DEPENDENCIES_SOURCE_DIR}/pthreadpool"
	BINARY_DIR "${CONFU_DEPENDENCIES_BINARY_DIR}/pthreadpool"
	CONFIGURE_COMMAND ""
	BUILD_COMMAND ""
	INSTALL_COMMAND ""
	TEST_COMMAND ""
)
